apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/TALBIHafsa/workshop-service-volet2.git"
    targetRevision: HEAD
    path: "."
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pitstop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
